sudo: required

language: c

services:
  - docker

before_install:
  - docker pull esguerra/q6
#  - docker run -i esguerra/q6 bash -c "cd /root/q6/src; source ~/.bashrc; export; module load mpi/openmpi-x86_64; make all COMP=gcc; make mpi COMP=gcc;  cd ../tests/test1; ./run_test_mpi.sh"
  - docker run --cpuset-cpus="0-3" -i esguerra/q6 bash -c "cd /root/q6/src; source ~/.bashrc; export; cd ../tests/test1; ./run_test_mpi.sh; cat eq1.log"
  - docker ps -a
  - docker images -a
script:
#  - docker run esguerra/q6 bash -c "cd /root/q6/tests/test1; source ~/.bashrc; module load mpi/openmpi-x86_64; module list; ls ../../bin"
# notice that if there's no docker call the commands are local to the travis machine, generally a ubuntu type.
  - export
#  - pwd

#script:
#  - cd tests/test1
#  - ./run_tests
#after_success:
#  - cd $TEST_DIR
#  - rm *.log *.dcd *.en



