sudo: required

language: c

services:
  - docker

before_install:
- docker pull esguerra/docker-fed27gcc
- docker run esguerra/docker-fed27gcc /bin/sh -c "cd /root/Q6/src"
- docker ps -a

script:
  - make all COMP=gcc
  - make mpi COMP=gcc

#script:
#  - cd tests/test1
#  - ./run_tests
#after_success:
#  - cd $TEST_DIR
#  - rm *.log *.dcd *.en



