language: c
addons:
  apt:
    packages:
    - gcc
    - gfortran
    - binutils
install:
  - cd src
  - make all COMP=gcc
  - cd ..
#script:
#  - cd tests/test1
#  - ./run_tests
#after_success:
#  - cd $TEST_DIR
#  - rm *.log *.dcd *.en



