sudo: required

language: c

services:
  - docker

before_install:
- docker pull esguerra/q6
- docker run esguerra/q6 bash -c "cd /root/q6/src; source ~/.bashrc; export; module load mpi/openmpi-x86_64; make all; make mpi"
- docker ps -a

script:
#  - cd /root/q6/src
  - source ~/.bashrc
  - export
#  - module load mpi/openmpi-x86_64
#  - make all COMP=gcc
#  - make mpi COMP=gcc

#script:
#  - cd tests/test1
#  - ./run_tests
#after_success:
#  - cd $TEST_DIR
#  - rm *.log *.dcd *.en



