sudo: required

language: c

services:
  - docker

before_install:
- docker pull esguerra/q6
- docker run esguerra/q6 /bin/sh -c "cd /root/Q6/src; make all COMP=gcc; make mpi COMP=gcc"
- docker ps -a


script:
  - make all COMP=gcc
  - make mpi COMP=gcc

#script:
#  - cd tests/test1
#  - ./run_tests
#after_success:
#  - cd $TEST_DIR
#  - rm *.log *.dcd *.en



